export const ROUTES = {
    HOME: '/',
    ABOUT: '/#about',
    CATEGORIES_TOURISM: '/categories/tourism',
    CATEGORIES_WAREHOUSING: '/categories/warehousing',
    CATEGORIES_CONSTRUCTION: '/categories/construction',
    CATEGORIES_CLEANING: '/categories/cleaning',
    CATEGORIES_HOSPITALITY: '/categories/hospitality',
    CONTACT: '/#contact',
    LOGIN: '/login',
    COMING_SOON: '/coming-soon',
    BLOG: '/blog',
    FAQS: '/faqs',
    ENTRY: '/blog/entry',
    SIGN_UP: '/sign-up',
    TERMS: '/terms',
    PRIVACY_POLICY: '/privacy-policy',
    //Private routes
    MY_PROFILE: 'dashboard/my-profile',
}
