const STAFF_RESULTS = [
    {
        name: 'Juan',
        profileImage: '/assets/images/search/barista-1.png',
        age: 24,
        rol: 'Barista',
        city: 'Melbourne',
        state: 'VIC',
        cp: '3000',
        rate: '97',
        reviews: '6',
    },
    {
        name: 'Shane',
        profileImage: '/assets/images/search/barista-2.png',
        age: 28,
        rol: 'Barista',
        city: 'St Klida',
        state: 'VIC',
        rate: '95',
        cp: '3182',
        reviews: '11',

    },
    {
        name: 'Diana',
        profileImage: '/assets/images/search/barista-3.png',
        age: 26,
        rol: 'Barista',
        city: 'Elwood',
        state: 'VIC',
        rate: '92',
        cp: '3065',
        reviews: '3',

    },
    {
        name: 'Johanna',
        profileImage: '/assets/images/search/barista-4.png',
        age: 27,
        rol: 'Barista',
        city: 'Brighton',
        state: 'VIC',
        rate: '91',
        cp: '3186',
        reviews: '5',
    },
    {
        name: 'Nadia',
        profileImage: '/assets/images/search/barista-5.png',
        age: 22,
        rol: 'Barista',
        city: 'Kew',
        state: 'VIC',
        rate: '90',
        cp: '3101',
        reviews: '10',
    },
    {
        name: 'Sonia',
        profileImage: '/assets/images/search/barista-6.png',
        age: 29,
        rol: 'Barista',
        city: 'Malvern',
        state: 'VIC',
        rate: '88',
        cp: '3144',
        reviews: '15',
    },
    {
        name: 'Ben',
        profileImage: '/assets/images/search/barista-7.png',
        age: 27,
        rol: 'Barista',
        city: 'Docklands',
        state: 'VIC',
        rate: '87',
        cp: '3008',
        reviews: '21',
    },
    {
        name: 'Anna',
        profileImage: '/assets/images/search/barista-8.png',
        age: 24,
        rol: 'Barista',
        city: 'Yarraville',
        state: 'VIC',
        rate: '86',
        cp: '3013',
        reviews: '0',
    },
    {
        name: 'Dominic',
        profileImage: '/assets/images/search/barista-9.png',
        age: 32,
        rol: 'Barista',
        city: 'Prahran',
        state: 'VIC',
        rate: '84',
        cp: '3181',
    },
    {
        name: 'Ruth',
        profileImage: '/assets/images/search/barista-10.png',
        age: 25,
        rol: 'Barista',
        city: 'Brighton East',
        state: 'VIC',
        rate: '84',
        cp: '3008',
        reviews: '7',
    },
    {
        name: 'Laura',
        profileImage: '/assets/images/search/barista-11.png',
        age: 21,
        rol: 'Barista',
        city: 'Brighton East',
        state: 'VIC',
        rate: '83',
        cp: '3187',
        reviews: '2',
    },
    {
        name: 'Carlos',
        profileImage: '/assets/images/search/barista-12.png',
        age: 32,
        rol: 'Barista',
        city: 'Ormond',
        state: 'VIC',
        rate: '82',
        cp: '3204',
        reviews: '5',
    },
    {
        name: 'Beth',
        profileImage: '/assets/images/search/barista-13.png',
        age: 28,
        rol: 'Barista',
        city: 'Brighton East',
        state: 'VIC',
        rate: '81',
        cp: '3008',
        reviews: '2',
    },
    {
        name: 'Stephanie',
        profileImage: '/assets/images/search/barista-14.png',
        age: 24,
        rol: 'Barista',
        city: 'Yarraville',
        state: 'VIC',
        rate: '80',
        cp: '3013',
        reviews: '3',
    },
    {
        name: 'Endo',
        profileImage: '/assets/images/search/barista-15.png',
        age: 27,
        rol: 'Barista',
        city: 'Albert Park',
        state: 'VIC',
        rate: '79',
        cp: '3206',
        reviews: '10',
    },
]

const BUSINESS_RESULTS = [
    {
        name: 'The Timbuktu Cafe',
        profileImage: '/assets/images/business/business-1.png',
        city: 'Brighton',
        state: 'VIC',
        cp: '3181',
        rate: '97',
        reviews: '2',
    },
    {
        name: 'The Baths Middle Brighton',
        profileImage: '/assets/images/business/business-2.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '95',
        cp: '3181',
        reviews: '5',
    },
    {
        name: 'Mylk Cafe',
        profileImage: '/assets/images/business/business-3.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '92',
        cp: '3186',
        reviews: '7',
    },
    {
        name: 'Holy Grounds Cafe',
        profileImage: '/assets/images/business/business-4.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '91',
        cp: '3181',
        reviews: '1',
    },
    {
        name: 'Brighton Soul Espresso',
        profileImage: '/assets/images/business/business-5.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '90',
        cp: '3181',
        reviews: '9',
    },
    {
        name: 'Pantry Brighton',
        profileImage: '/assets/images/business/business-6.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '88',
        cp: '3186',
    },
    {
        name: "Ninna's Kitchen",
        profileImage: '/assets/images/business/business-7.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '87',
        cp: '3181',
        reviews: '12',
    },
    {
        name: 'Laurent Bakery Brighton',
        profileImage: '/assets/images/business/business-8.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '85',
        cp: '3181',
        reviews: '4',
    },
    {
        name: 'Blitz Bar Brighton',
        profileImage: '/assets/images/business/business-9.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '84',
        cp: '3186',
        reviews: '16',
    },
    {
        name: 'Dendy Deli',
        profileImage: '/assets/images/business/business-10.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '84',
        cp: '3181',
        reviews: '1',
    },
    {
        name: 'Botticelli of Brighton',
        profileImage: '/assets/images/business/business-11.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '82',
        cp: '3181',
        reviews: '3',
    },
    {
        name: 'Waterfront Brighton',
        profileImage: '/assets/images/business/business-12.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '80',
        cp: '3186',
        reviews: '8',
    },
    {
        name: 'Superrandom',
        profileImage: '/assets/images/business/business-13.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '79',
        cp: '3181',
        reviews: '14',
    },
    {
        name: 'The Little Ox',
        profileImage: '/assets/images/business/business-14.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '78',
        cp: '3181',
        reviews: '11',
    },
    {
        name: "Saint Martin's",
        profileImage: '/assets/images/business/business-15.png',
        city: 'Brighton',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '9',
    },
]

const LICENCES_RESULTS = [
    {
        name: "Basic Espresso",
        profileImage: '/assets/images/licences/licences-1.png',
        institution: 'Melbourne Coffe Academy',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '28',
    },
    {
        name: "Latte Art",
        profileImage: '/assets/images/licences/licences-2.png',
        institution: 'Melbourne Coffe Academy',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '52',
    },
    {
        name: "Advaned Espresso",
        profileImage: '/assets/images/licences/licences-3.png',
        institution: 'Melbourne Coffe Academy',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '35',
    },
    {
        name: "Nationaly Recognised...",
        profileImage: '/assets/images/licences/licences-4.png',
        institution: 'Australian Barista School',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '12',
    },
    {
        name: "Coffe Appreciation",
        profileImage: '/assets/images/licences/licences-5.png',
        institution: 'Melbourne Coffe Academy',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '26',
    },
    {
        name: "Barista Course National",
        profileImage: '/assets/images/licences/licences-6.png',
        institution: 'Australian Barista School',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '47',
    },
    {
        name: "Barista Masterclass",
        profileImage: '/assets/images/licences/licences-7.png',
        institution: 'Melbourne Coffe Academy',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '38',
    },
    {
        name: "RSA & Barista Package",
        profileImage: '/assets/images/licences/licences-8.png',
        institution: 'Australian Barista School',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '19',
    },
    {
        name: "Barista Coffee Making",
        profileImage: '/assets/images/licences/licences-9.png',
        institution: 'Barista Course Melbourne',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '34',
    },
    {
        name: "Coffee Art",
        profileImage: '/assets/images/licences/licences-10.png',
        institution: 'Barista Course Melbourne',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '25',
    },
    {
        name: "How to Make Espresso",
        profileImage: '/assets/images/licences/licences-11.png',
        institution: 'Market Lane Coffe',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '14',
    },
    {
        name: "Barista Coffee Course",
        profileImage: '/assets/images/licences/licences-12.png',
        institution: 'Short Courses Australia',
        city: 'Melbourne',
        state: 'VIC',
        rate: '75',
        cp: '3186',
        reviews: '31',
    },
]

export {
    STAFF_RESULTS,
    BUSINESS_RESULTS,
    LICENCES_RESULTS,
}